version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
  qdrant:
    image: qdrant/qdrant:v1.9
    ports:
      - "6333:6333"
  redis:
    image: redis:7
    ports:
      - "6379:6379" 